---
swagger: '2.0'
info:
  version: 1.0.0
  title: Fish History
paths:
  /history/chunk:
    post:
      produces:
        - application/json
      parameters:
        - name: body
          required: true
          in: body
          schema:
            $ref: "#/definitions/ChunkHistoryParams"
      operationId: chunkHistory
      responses:
        200:
          description: 'History blocks filtered.'
          schema:
            $ref: "#/definitions/HistoryBlocks"
        400:
          description: 'Bad request.'

definitions:
  TimeUnit:
    type: string
    enum:
      - all
      - year
      - month
      - week
      - day
      - hour
      - minute
      - second
    default: all
  Timestamp:
    type: integer
    format: int64
    description: 'Timestamp in unixtime seconds.'
  TimestampNullable:
    type: integer
    format: int64
    description: 'Timestamp in unixtime seconds.'
    x-nullable: true
  TimeRangeFilter:
    type: object
    properties:
      from:
        $ref: "#/definitions/TimestampNullable"
      to:
        $ref: "#/definitions/TimestampNullable"
  ChunkHistoryParams:
    type: object
    properties:
      unit:
        $ref: "#/definitions/TimeUnit"
      filter:
        $ref: "#/definitions/TimeRangeFilter"
      limit:
        type: integer
        description: 'Limit number of results in a single chunk. Undefined means +inf.'
        x-nullable: true
  HistoryBlocks:
    type: object
    required:
      - unit
    properties:
      unit:
        $ref: "#/definitions/TimeUnit"
      blocks:
        type: array
        minItems: 1
        items:
          $ref: "#/definitions/HistoryBlock"
  HistoryBlock:
    type: object
    required:
      - count
      - from
      - to
    properties:
      count:
        type: integer
      histories:
        type: array
        minItems: 1
        items:
          $ref: "#/definitions/History"
      from:
        $ref: "#/definitions/Timestamp"
      to:
        $ref: "#/definitions/Timestamp"
  History:
    type: object
    required:
      - when
      - cmd
    properties:
      when:
        $ref: "#/definitions/Timestamp"
      cmd:
        type: string
      paths:
        type: array
        minItems: 1
        items:
          type: string
