name: release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.13.0
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --prefer-offline]
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - run: make build
      - name: Check version info is latest
        working-directory: ./projects/cli
        run: |
          VERSION="$(go run main.go -v)"
          GOT="refs/tags/v${VERSION}"
          WANT="${{ github.ref }}"
          if test "${GOT}" != "${WANT}"; then
            echo "Version check fail."
            echo "Got: ${Got}"
            echo "Want: ${WANT}"
            exit 1
          fi
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
          workdir: ./projects/cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
